カレンダープログラムの提出
kasai441/ruby-practices pull request #2
Opened 2021-01-20 04:07 UTC by kasai441

よろしくお願いします

optparseライブラリを使用せずに作業を進めてしまいましたが、仕様はこれで満たしていると思うので、いったんこれで提出します。もしライブラリの導入が必須な場合は作り直します。

2021-01-24 04:19 UTC, torinoko requested changes
@kasai441 
インデントが崩れている場所がいくつかあるので確認と修正をお願いします！
（タブになっているようなので、エディタの設定を見直すといいかもしれませんね）

あとこれはクセとしてつけておくとよいのですが、以下のタイミングで差分や変更内容をチェックするとよいですよ〜。

- `git commit` する前（ `git diff` で必ず差分確認）
- Pull Request でレビューを依頼する前（ Files changed を確認）

2021-01-24 04:19 UTC, torinoko commented on 02.calendar/cal.rb
> +def twoLetter(str)
Ruby の場合、メソッド名はスネークケースで書く方が一般的です。

2021-01-24 04:19 UTC, torinoko commented on 02.calendar/cal.rb
> +      write_week += " " * 2
最初の週の処理ですかね。
ここをループの外で処理するとフラグや分岐がなくなるので、ループがすっきりするかもしれませんね。

2021-01-25 07:14 UTC, kasai441 commented on 02.calendar/cal.rb
> +  str = str.to_s
キャメルケースからスネークケース

2021-01-25 07:17 UTC, kasai441 commented on 02.calendar/cal.rb
> +def keep_two_letter(str)
キャメルケースからスネークケース

2021-01-25 07:18 UTC, kasai441 commented on 02.calendar/cal.rb
> +  end
タブから空白へ

2021-01-25 07:20 UTC, kasai441 commented on 02.calendar/cal.rb
> +write_week += '日 月 火 水 木 金 土  ' + "\n"
ループ処理で面倒な判定を行わないために、
週ごとのstring配列から、すべて文字列に変更

2021-01-25 07:20 UTC, kasai441 commented on 02.calendar/cal.rb
> +puts write_week
ループ処理で面倒な判定を行わないために、
週ごとのstring配列から、すべて文字列に変更

2021-01-25 07:26 UTC, kasai441 commented
@torinoko 
レビューありがとうございます！
指摘事項修正しました。
ループの処理は複雑なフラグ処理をなくすためにString配列の形ではなくすべて一つの文字列でデータをつくる形に変更しました。
また、ただの文字列の定義を「"」から「'」に変更しています。

2021-01-25 07:52 UTC, kasai441 commented
ちなみに、fizzbuzzの時に間違ってmainにファイル作成コミットしたものをrevertしています。

2021-01-25 11:57 UTC, torinoko approved these changes
@kasai441 
よいと思います！
Date クラスの機能をいろいろ使うと、もっとすっきり書けそうですね。
解答例もぜひご覧になってくださいね。

2021-01-25 11:57 UTC, torinoko commented on 02.calendar/cal.rb
> +  end
これでも OK ですが、曜日を取得できるともっと楽できそうな気がします ☺️ 
https://docs.ruby-lang.org/ja/latest/class/Date.html

2021-01-26 00:46 UTC, kasai441 commented on 02.calendar/cal.rb
> +write_week += write_blank_day(write_date.cwday)
余計な変数cwを使用せず、Date.cwdayで統一

2021-01-26 00:46 UTC, kasai441 commented on 02.calendar/cal.rb
> +  end
余計な変数cwを使用せず、Date.cwdayで統一

2021-01-26 00:46 UTC, kasai441 commented on 02.calendar/cal.rb
> +write_week += write_blank_day(7 - write_date.cwday) + ' '
余計な変数cwを使用せず、Date.cwdayで統一

2021-01-26 01:10 UTC, kasai441 commented
@torinoko 
> Date クラスの機能をいろいろ使うと、もっとすっきり書けそうですね。
書き直してみました！OK頂いた後ですみませんー

ちなみに@torinokoさんのように一つのConversationコメントにほかの変更を含む方法がわからなかったのでQ&Aに起票してみました。
https://bootcamp.fjord.jp/questions/785

2021-01-26 04:18 UTC, torinoko approved these changes
変数が減ったので見やすくなりましたね！🎉

2021-01-28 13:58 UTC, merged